<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('valuation_assignments', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->uuid('tenant_id');
            $table->uuid('organization_id')->nullable(); // the valuation firm branch handling it
            $table->uuid('organization_branch_id')->nullable();

            // Human-readable, tenant + fiscal-year scoped, e.g. VAL-2083-000001.
            // Generated by AssignmentNumberGenerator, never client-supplied.
            $table->string('assignment_number');
            $table->foreignId('fiscal_year_id')->constrained('fiscal_years');

            $table->uuid('client_id');
            $table->uuid('client_branch_id')->nullable();
            $table->date('assignment_date');
            $table->date('requested_completion_date')->nullable();
            $table->string('priority')->default('normal'); // low|normal|high|urgent
            $table->foreignId('valuation_purpose_id')->constrained('valuation_purposes');
            $table->string('loan_application_number')->nullable();
            $table->uuid('borrower_id')->nullable();
            $table->string('contact_person')->nullable();
            $table->decimal('requested_loan_amount', 18, 2)->nullable();

            $table->uuid('assigned_valuer_id')->nullable();
            $table->uuid('assigned_surveyor_id')->nullable();
            $table->uuid('assigned_reviewer_id')->nullable();
            $table->uuid('assigned_approver_id')->nullable();

            $table->decimal('assignment_fee', 14, 2)->default(0);
            $table->decimal('travel_fee', 14, 2)->default(0);
            $table->decimal('additional_charges', 14, 2)->default(0);
            $table->decimal('vat_amount', 14, 2)->default(0);
            $table->decimal('discount_amount', 14, 2)->default(0);
            $table->decimal('total_fee', 14, 2)->default(0);
            $table->string('payment_status')->default('unpaid'); // unpaid|partially_paid|paid|overdue

            // Current workflow status code -- always kept consistent with the
            // latest workflow_transitions row by WorkflowEngine::transition();
            // never written directly anywhere else in the codebase.
            $table->string('status')->default('draft');
            $table->unsignedInteger('sla_duration_hours')->nullable();
            $table->timestamp('sla_due_at')->nullable();

            $table->string('instruction_letter_path')->nullable();
            $table->text('client_remarks')->nullable();
            $table->text('internal_remarks')->nullable();
            $table->text('cancellation_reason')->nullable();

            $table->boolean('is_revaluation')->default(false);
            $table->uuid('parent_assignment_id')->nullable();

            $table->timestamps();
            $table->softDeletes();

            $table->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete();
            $table->foreign('organization_id')->references('id')->on('organizations')->nullOnDelete();
            $table->foreign('organization_branch_id')->references('id')->on('organization_branches')->nullOnDelete();
            $table->foreign('client_id')->references('id')->on('clients')->restrictOnDelete();
            $table->foreign('client_branch_id')->references('id')->on('client_branches')->nullOnDelete();
            $table->foreign('borrower_id')->references('id')->on('borrowers')->nullOnDelete();
            $table->foreign('assigned_valuer_id')->references('id')->on('users')->nullOnDelete();
            $table->foreign('assigned_surveyor_id')->references('id')->on('users')->nullOnDelete();
            $table->foreign('assigned_reviewer_id')->references('id')->on('users')->nullOnDelete();
            $table->foreign('assigned_approver_id')->references('id')->on('users')->nullOnDelete();
            $table->foreign('parent_assignment_id')->references('id')->on('valuation_assignments')->nullOnDelete();

            $table->unique(['tenant_id', 'assignment_number']);
            $table->index(['tenant_id', 'status']);
        });

        Schema::create('assignment_properties', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->uuid('tenant_id');
            $table->uuid('valuation_assignment_id');
            $table->uuid('property_id');
            $table->unsignedSmallInteger('sequence')->default(1);
            $table->timestamps();

            $table->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete();
            $table->foreign('valuation_assignment_id')->references('id')->on('valuation_assignments')->cascadeOnDelete();
            $table->foreign('property_id')->references('id')->on('properties')->cascadeOnDelete();
            $table->unique(['valuation_assignment_id', 'property_id']);
        });

        Schema::create('assignment_property_owners', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->uuid('tenant_id');
            $table->uuid('assignment_property_id');
            $table->uuid('property_owner_id');
            $table->timestamps();

            $table->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete();
            $table->foreign('assignment_property_id')->references('id')->on('assignment_properties')->cascadeOnDelete();
            $table->foreign('property_owner_id')->references('id')->on('property_owners')->cascadeOnDelete();
            $table->unique(['assignment_property_id', 'property_owner_id'], 'assignment_property_owner_unique');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('assignment_property_owners');
        Schema::dropIfExists('assignment_properties');
        Schema::dropIfExists('valuation_assignments');
    }
};
